// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icmekjangpskaoixwopq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljbWVramFuZ3Bza2FvaXh3b3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNzU1NzcsImV4cCI6MjA2Mjg1MTU3N30.Z_XL76eAagqyt4oAHTfFcISqTdraHsfsNetHtUjR2qw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);